baseurl = "https://ocul.on.ca/topomaps/"
#baseurl = "https://staticdev.scholarsportal.info/topomaps/"
#baseurl = "http://localhost/hist-topos/public/"
theme = "hugo-creative-portfolio-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
canonifyURLs = false
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[markup.goldmark.renderer]
    unsafe = true

[params]
    logourl = "https://ocul.on.ca"
    style = "blue"
    email = "topomaps@scholarsportal.info"

# Optional piwik tracking
[params.analytics.piwik]
    URL = "https://analytics.scholarsportal.info"
    ID = "59"

[params.social]
    github = "https://github.com/scholarsportal/historical-topos"
    email = "topomaps@scholarsportal.info"

[Languages]

    [Languages.en]
        languageName = "English"
        title = "Historical Topographic Map Digitization Project"
        languageCode = "en"
        weight = 1
        logo = "img/ocul.png"
        logoalt = "Ontario Council of University Libraries"
        [[Languages.en.navlinks]]
            name = "Home"
            url = ""
        [[Languages.en.navlinks]]
            name = "About the Project"
            url = "about-project/"
        [[Languages.en.navlinks]]
            name = "About the Maps"
            url = "about-maps/"
        [[Languages.en.navlinks]]
            name = "Collection Highlights"
            url = "highlights/"
        [[Languages.en.navlinks]]
            name = "Using the Maps"
            url = "using-maps/"
        [[Languages.en.navlinks]]
            name = "Full Collection"
            url = "collection/"
        [[Languages.en.navlinks]]
            name = "FAQ"
            url = "faq/"
        [[Languages.en.navlinks]]
            name = "Contact"
            url = "contact/"

    [Languages.fr]
        languageName = "Français"
        title = "Projet de numérisation de la carte topographique historique"
        languageCode = "fr"
        weight = 2
        logo = "img/cbou.png"
        logoalt = "Conseil des bibliothèques universitaires de l'Ontario"
        [[Languages.fr.navlinks]]
            name = "Accueil"
            url = "fr/"
        [[Languages.fr.navlinks]]
            name = "À propos du projet"
            url = "fr/about-project/"
        [[Languages.fr.navlinks]]
            name = "Au sujet des cartes"
            url = "fr/about-maps/"
        [[Languages.fr.navlinks]]
            name = "Points saillants de la collection"
            url = "fr/highlights/"
        [[Languages.fr.navlinks]]
            name = "Utiliser les cartes"
            url = "fr/using-maps/"
        [[Languages.fr.navlinks]]
            name = "Parcourir la collection au complet"
            url = "fr/collection/"
        [[Languages.fr.navlinks]]
            name = "FAQ"
            url = "fr/faq/"
        [[Languages.fr.navlinks]]
            name = "Nous contacter"
            url = "fr/contact/"